### ISSUE TITLE
na.kalman function modified the original numeric vector

### ISSUE THREAD

**Issue by yuchenw** [SteffenMoritz/imputeTS#12]
Dear Mr. Moritz,

I am testing the `na.kalman` function from the `imputeTS` package. It seems like after running the na.kalman and saving the outcome to a new variable, it also changes the original numeric vector. I described this behavior in this post (http://stackoverflow.com/questions/43478244/strange-behavior-of-the-na-kalman-function-from-the-r-imputets-package) with more details. Could you check if there is a way to ask na.kalman not to change the original vector?

Thank you for your time and consideration.

All the best

Yu-Chen

**Comment by SteffenMoritz** [comment]
Thanks a lot for your post!
This is indeed a bug.
(which appeared for na.kalman and na.locf for some parameter settings)

I directly fixed it :-)
If you install the package directly from Github you can already have the update.

library(devtools)
install_github("SteffenMoritz/imputeTS")

 I will also upload the 2.2 Version that includes this bugfix by the end of the week.

**Comment by yuchenw** [comment]
Thank you for your prompt reply and update of the imputeTS package! I have downloaded the version from the Github. It works!
