### ISSUE TITLE
Need libcurl development package to install

### ISSUE THREAD

**Issue by dotwilbert** [SteffenMoritz/imputeTS#21]
The first attempt of installation failed, because the installation of dependencies failed. Turned out you need a development package of libcurl to build. Although in the messages that fly by on the screen do mention
```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```
the conclusion at the end of the high-speed scrolling do not. Would it be possible to mention this in the installation notes?

**Comment by SteffenMoritz** [comment]
Hello dotwilbert, thanks a lot for your feedback.
Unfortunately I could not replicate the problem. 

You could help me by providing additional infos :)
1. What operating system do you use.
2. Do you still have the complete installation messages?

**Comment by SteffenMoritz** [comment]
I'll close this for now, since I can't check this without further feedback. If somebody has the same problem it would be great if you can open a new Issue. 
@dotwilbert would still be great if you can provide the additional information once you have some time. You can write per mail to steffen.moritz10 at gmail.com
