### ISSUE TITLE
Package install error

### ISSUE THREAD

**Issue by sakdaloet** [SteffenMoritz/imputeTS#22]
Hi
I'm try to install >install_github("SteffenMoritz/imputeTS")<
but error ocurred
how to fix it

Thanks
Sakda

2018-06-07 14:31:47 (1.35 MB/s) - ‘/tmp/RtmprcTMQj/forecast_8.3.tar.gz’ saved [601570/601570]

Installing forecast
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmprcTMQj/devtools21d72e52dd39/forecast'  \
  --library='/home/---/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

ERROR: dependency ‘RcppArmadillo’ is not available for package ‘forecast’
* removing ‘/home/---/R/x86_64-pc-linux-gnu-library/3.2/forecast’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmprcTMQj/devtools21d766fca16e/SteffenMoritz-imputeTS-d6a032e'  \
  --library='/home/--/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

ERROR: dependency ‘forecast’ is not available for package ‘imputeTS’
* removing ‘/home/--/R/x86_64-pc-linux-gnu-library/3.2/imputeTS’
Installation failed: Command failed (1)

**Comment by SteffenMoritz** [comment]
Does an install from CRAN give the same result?
install.packages("imputeTS")

**Comment by SteffenMoritz** [comment]
I'll close this since no further input came. Seems like a problem installing forecast, which is a dependency of imputeTS.
Here is a link, how this may be solved:
https://developer.ibm.com/answers/questions/289852/forecast-and-rcpparmadillo-package-installation-is/
