### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by shreydesai** [SteffenMoritz/imputeTS#23]
Minor, but spelling mistakes in the error messages below. Change "saisonal" to "seasonal".

https://github.com/SteffenMoritz/imputeTS/blob/master/R/na.seadec.R#L101
https://github.com/SteffenMoritz/imputeTS/blob/master/R/na.seasplit.R#L105

**Comment by SteffenMoritz** [comment]
Hey shreydesai thanks a lot!  I fixed it for the development version on GitHub. CRAN fix will come with the next update :)

**Comment by shreydesai** [comment]
Make sure to add a period in this sentence :)

https://github.com/SteffenMoritz/imputeTS/blob/master/R/na.seasplit.R#L105

**Comment by SteffenMoritz** [comment]
One error fixed - another error added ... fail xD  Thanks again. Now it should be fixed ;)

**Comment by SteffenMoritz** [comment]
Also on CRAN now :-)
https://cran.r-project.org/web/packages/imputeTS/news/news.html
