### ISSUE TITLE
Stineman interpolation throwing error

### ISSUE THREAD

**Issue by Breza** [SteffenMoritz/imputeTS#28]
I'm getting the following error when I try to use Stineman interpolation. I switched to a spline without affecting my data, but I wanted to document that this isn't working for me.

```
imputeTS::na.interpolation(site$t_hr_avg, option = "stein")
Error in imputeTS::na.interpolation(site$t_hr_avg, option = "stein") : 
Wrong parameter 'option' given. Value must be either 'linear' or 'spline'.
```

**Comment by SteffenMoritz** [comment]
Thanks a lot! You actually have a spelling error in your code.
It has to be "stine". (you wrote "stein").

Still, thanks a lot for opening this issue, I took this as hint to improve the error message.
With the next update of imputeTS the message will be "Wrong parameter 'option' given. Value must be either 'linear', 'spline' or 'stine'."

**Comment by Breza** [comment]
Thank you for your kind reply to my obvious mistake 😄

**Comment by SteffenMoritz** [comment]
"With the next update of imputeTS the message will be "Wrong parameter 'option' given. Value must be either 'linear', 'spline' or 'stine'." <- on CRAN now

**Comment by Breza** [comment]
Awesome! I really appreciate your making a patch instead of just saying "Issue closed, user error."
