### ISSUE TITLE
Multiple seasonality handling msts

### ISSUE THREAD

**Issue by gucoloradoc** [SteffenMoritz/imputeTS#33]
Hi, is it possible to do a seasonal decomposition imputation for complex time series (msts class)?. For example a time series that has a hourly, weekly and yearly seasonality. Thanks!

**Comment by SteffenMoritz** [comment]
Hello @gucoloradoc, thanks for your question.
Interesting topic, unfortunately it is currently not possible (in the imputeTS package).
As far as I know - also no other package is providing this in an easy to use way.

In general the implementation should be not too complicated.
With the msts object you'd have to use the mstl() function from the forecast package for the decomposition. Then you remove all seasonal + trend components - afterwards perform e.g. linear interpolation and then add the seasonal + trend components again.

You were the first one asking about msts objects. 
I'll keep an eye on this! :)
If there are more people interested in multi seasonal time series in the future it is certainly a good idea adding this to the package.

**Comment by gucoloradoc** [comment]
Hi Steffen, thanks for your prompt response. You gave me a good idea to perform the imputation and thanks for the package, very useful!.

Best regards,
Gerson
