### ISSUE TITLE
could not find function "na_interpolation"

### ISSUE THREAD

**Issue by hariskr** [SteffenMoritz/imputeTS#34]
Until a few days ago I could use na.interpolation function just fine... Today it stopped working so I looked online and saw it was changed to na_interpolation. I tried this and it gave me the error:

Error in na.interpolation(comparSpline[v, ], option = "spline") : 
  could not find function "na.interpolation"

Is there a newer version of this function I am not aware of? As far as I can tell, the imputeTS package was successfully installed. I'm a bit lost. Thanks in advance for your help.

**Comment by SteffenMoritz** [comment]
Hi hariskr,
this is strange...the syntax is changed to na_interpolation but this shouldn't affect you.
(even in the newest version imputeTS 3.0 we enabled it that you can still use na.interpolation)

Can you do the following: 
     packageVersion("imputeTS")

Afterwards post it here.
Another hint, make sure you called library(imputeTS) before you use the function.
(this would be the most typical problem xD - you got a problem think about every possible super complex solution ... but miss the simple things)

Test it again after you called  library(imputeTS).

After you checked the version run:
install.packages("imputeTS") to get the newest version (3.0)

you can then run 
library("imputeTS")
na.interpolation(tsAirgap)

Would be interesting if this gives you output.

**Comment by hariskr** [comment]
Thanks, it looks like I was running v 2.7, but when I upgraded to 3.0 it worked
