### ISSUE TITLE
Suggestion: Applying the na_mean function considering only values from the same periods.

### ISSUE THREAD

**Issue by DyProject** [SteffenMoritz/imputeTS#49]
When using the na_mean function for a time series, I discovered the need to calculate the value of NAs considering only the previous values for the same period. For example, for a quarterly time series, with data for three years, and in the last year , all values are NAs. To calculate the value of each quarter, only the values referring to the same quarter of previous years are considered. Below is the example code:

data_ts <- ts(data = c(2,4,6,8, 4,12,14,16, NA,NA,NA,NA), frequency = 4)
dtmissing <- is.na(data_ts)
for (i in 1:frequency(data_ts)) {
  slcMonth <- cycle(data_ts) == i
  data_ts[slcMonth & dtmissing] <- median(data_ts[slcMonth & !dtmissing], na.rm = T) 
}

**Comment by SteffenMoritz** [comment]
Hello DyProject,

thanks a lot for your message!  

You'd be surprised, this is already possible.

You can use this code for mean:

`na_seasplit(data_ts, algorithm ="mean")`

or this for median

`na_seasplit(data_ts, algorithm ="mean", option = "median")
`
It does the same as you suggest, it only takes values of the same period (and then applies the algorithm you choose to create the imputations). Saying, it basically splits the series into periods and imputes each of these separately. You can additionally choose different algorithms and also add additional arguments.

So maybe this helps saving you some time the next time you need it. 

Thank you for opening an issue - even if the function is already there, this is still quite helpful for me. I'll keep this in mind for further versions, maybe I can improve the documentation to make this functionality of na_seasplit more obvious.
