### ISSUE TITLE
Converting from ee.Image data to Numeric Vector (vector) or Time Series (ts) object

### ISSUE THREAD

**Issue by eeedasc** [SteffenMoritz/imputeTS#65]
Hello everyone,
I have an 'ee.Image' data from MODIS Satellite. I'm writing my codes with 'rgee packages'. I want to calculate the missing values in the image using ImputeTS but firstly, I have to convert from ee.Image data to vector or ts object.
How can I do?
Thank you:)

**Comment by SteffenMoritz** [comment]
Hello, @eeedasc,
unfortunately I have no idea about rgee and working with google earth images. So, no idea how their format is structured. Sorry that I can't help you there. Hope you don't mind that I close this issue (as it is rather a rgee problem then imputeTS related). Hope it worked out in the end.
Best Steffen

**Comment by Rapsodia86** [comment]
Here is a function in rgee to get a raster from raster package: https://rdrr.io/github/ryali93/rgee/man/ee_as_raster.html 
Then from raster you can (or not, but if not then it will be slower) convert to terra::rast() and apply a function.
