### ISSUE TITLE
could not find function "ggplot_na_distribution2"

### ISSUE THREAD

**Issue by ballZing** [SteffenMoritz/imputeTS#66]
I get an error when I try to use the "ggplot_na_distribution2" function
`Error in ggplot_na_distribution2(tsNH4) : 
  could not find function "ggplot_na_distribution2"`

**Comment by SteffenMoritz** [comment]
Try to update to the latest imputeTS version. This should fix the issue.

**Comment by SteffenMoritz** [comment]
Seemed to have fixed the problem :)
As there are no further people reporting the same issue, I will close this now.
